org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.jvm.target=17
kotlin.experimental.tryK2=false
kapt.verbose=true
kapt.use.worker.api=true
kapt.incremental.apt=true

# ? Release keystore
RELEASE_STORE_FILE=D\:/Prasanth/AndroidStudioProjects/HinduPoojaApp/KEYS/release/ramakoti-release.jks
RELEASE_KEY_ALIAS=ramakoti
RELEASE_STORE_PASSWORD=Pr@Kol3@0109
RELEASE_KEY_PASSWORD=Pr@Kol3@0109

# ? Debug keystore
DEBUG_STORE_FILE=D\:/Prasanth/AndroidStudioProjects/HinduPoojaApp/KEYS/debug/ramakoti-debug.jks
DEBUG_KEY_ALIAS=androiddebugkey
DEBUG_STORE_PASSWORD=android
DEBUG_KEY_PASSWORD=android
